sudo: required
services:
    - docker

before_install:
    - docker build -t nero21/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nero21/docker-react npm run test -- --coverage


deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-411439937231"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"



DockerReact-env.eba-79m376yb.us-east-2.elasticbeanstalk.com